import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { ReactNode, Suspense } from "react"; // <-- Import Suspense here
import { Sidebar, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../../components/SideMenu"; // Your AppSidebar client component

// You had these unused in your ESLint output, make sure to apply them to your <html> or <body> tags
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // You might want to apply the font variables to your <html> tag
  
        <SidebarProvider>
          {/*
            Wrap AppSidebar with Suspense.
            The `fallback` prop will render on the server until the client-side JS for AppSidebar loads.
          */}
          <Suspense fallback={<div>Loading sidebar...</div>}> {/* <-- ADD SUSPENSE HERE */}
            <AppSidebar />
          </Suspense>

          <SidebarTrigger /> {/* This also should likely be wrapped in Suspense if it's a client component with hooks */}

          <div className="mx-5">
            {children}
          </div>
        </SidebarProvider>

  );
}